const { Survey } = require('../models');

const surveydata = [
  {
    name: 'Cardi B',
    ageRange: 29,
    temperature_pref: "65 and below",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Sporadic",
    parties: "Very social, all my friends have a key",
    cleanlinessLevel: "I clean once a week",
    moveInDate: "Immediately",
    relationshipStatus: "Prefer roommate not having a partner",
    sharingItems: "You do not touch my DARN stuff",
    livingStyle: "We will be friendly",
    drinkingHabits: "All the time",
    smoking: "Every dayyyyyyyyy",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Absolutely",
    petPeeves: "If you buy food and don't eat it.",
    timeSpentInApartment: "Go out 3-5 times a week",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/01-cardib.jpg',
    user_id: 1
  },
  {
    name: 'Obama',
    ageRange: 62,
    temperature_pref: "65-70",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "No parties",
    cleanlinessLevel: "Neat freak",
    moveInDate: "Next two-three months",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "Whatever is mine is yours!",
    livingStyle: "Yes, I would love that",
    drinkingHabits: "No",
    smoking: "Would prefer if my roommate does not smoke",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "People who like trump",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/02-obama.jpg',
    user_id: 2
  },
  {
    name: 'Megan Thee Stallion',
    ageRange: 28,
    temperature_pref: "70-75",
    pets: "Has pets, but can't live with other animals",
    sleepWakeHours: "I like late nights but still get up early",
    parties: "Very social, all my friends have a key",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Within the month",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We can occasionally talk",
    drinkingHabits: "Occasionally",
    smoking: "Occasionally",
    decorationStyle: "Bright colors (like hot pink bruh)",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Absolutely",
    petPeeves: "Unsolicited advice from Nicki Minaj",
    timeSpentInApartment: "Never in the apartment",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/03-megan.jpg',
    user_id: 3
  },
  {
    name: 'Gypsy Rose Blanchard',
    ageRange: 32,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "Not having freedom to do what I want",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/04-gypsy.jpg',
    user_id: 4
  }, 
  {
    name: 'Jonathan Jones',
    ageRange: 19,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "when people don't know me",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/05-jonathan.jpg',
    user_id: 5
  },
  {
    name: 'Emily Anderson',
    ageRange: 24,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "these low SALARIES",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/06-emily.jpg',
    user_id: 6
  },
  {
    name: 'Jim Smith',
    ageRange: 28,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "When people call me Jimmy",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/07-jim.jpg',
    user_id: 7
  },
  {
    name: 'Maria Gonzalez',
    ageRange: 34,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "hialeah",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/08-maria.jpg',
    user_id: 8
  },
  {
    name: 'Kevin Johnson',
    ageRange: 31,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "Miami traffic",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/09-kevin.jpg',
    user_id: 9
  },
  {
    name: 'Gertrude Walters',
    ageRange: 90,
    temperature_pref: "65-70",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "CHILDREN and BABIES and YOUNG PEOPLE IN THE RETIREMENT HOME",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/10-gertrude.jpg',
    user_id: 10
  },
  {
    name: 'Justin Drew Bieber',
    ageRange: 29,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "My ex",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/11-justin.jpg',
    user_id: 11
  },
  {
    name: 'Archibald Cyrus Kennedy VI',
    ageRange: 37,
    temperature_pref: "75-80",
    pets: "Has pets, open to living with others",
    sleepWakeHours: "Morning person",
    parties: "Maybe once a month a friend will stop by",
    cleanlinessLevel: "Fairly clean, occasionally messy",
    moveInDate: "Immediately",
    relationshipStatus: "Okay with roommate having a partner",
    sharingItems: "I would prefer if you ask",
    livingStyle: "We just live together and that’s it",
    drinkingHabits: "No",
    smoking: "No",
    decorationStyle: "Neutral colors",
    cleaningTasks: "I’ll clean my stuff, you clean yours",
    bathroom: "Yes, but I can share if I have to",
    petPeeves: "Archibald Cyrus Kennedy V",
    timeSpentInApartment: "Going out on weekends",
    politicalStatus: "right",
    preferredAgeRange: null,
    profilePic: '/images/12-archibald.jpg',
    user_id: 12
  },
];

const seedSurvey = () => Survey.bulkCreate(surveydata);

module.exports = seedSurvey;
