const { Survey } = require('../models');

const surveydata = [
  {
    name: 'Cardi B',
    //age: 29,
    temperature_pref: "65 and below",
    pets: "has-pets-open",
    sleepWakeHours: "sporadic",
    parties: "very-social",
    cleanlinessLevel: "clean-once-a-week",
    moveInDate: "immediately",
    relationshipStatus: "prefer-no-partner",
    sharingItems: "do-not-touch-my-stuff",
    livingStyle: "be-friendly",
    drinkingHabits: "drink-all-the-time",
    smoking: "smoke-every-day",
    decorationStyle: "neutral-colors",
    cleaningTasks: "clean-individual-stuff",
    bathroom: "absolutely",
    petPeeves: "If you buy food and don't eat it.",
    timeSpentInApartment: "3-5-times-a-week",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/01-cardib.jpg'
  },
  {
    name: 'Obama',
    //age: 62,
    temperature_pref: "65-70",
    pets: "has-pets-open",
    sleepWakeHours: "morning-person",
    parties: "no-parties",
    cleanlinessLevel: "neat-freak",
    moveInDate: "next-2-3-months",
    relationshipStatus: "okay-with-partner",
    sharingItems: "whatever-is-mine-is-yours",
    livingStyle: "love-to-be-friends",
    drinkingHabits: "drink-no",
    smoking: "prefer-no-smoking",
    decorationStyle: "neutral-colors",
    cleaningTasks: "clean-50-50",
    bathroom: "preferable",
    petPeeves: "People who like trump",
    timeSpentInApartment: "weekends-out",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/04-obama.jpg'
  },
  {
    name: 'Megan Thee Stallion',
    //age: 28,
    temperature_pref: "70-75",
    pets: "has-pets-cant-live",
    sleepWakeHours: "late-nights-early-mornings",
    parties: "very-social",
    cleanlinessLevel: "fairly-clean-occasionally-messy",
    moveInDate: "within-a-month",
    relationshipStatus: "okay-with-partner",
    sharingItems: "prefer-ask",
    livingStyle: "occasionally-talk",
    drinkingHabits: "drink-occasionally",
    smoking: "smoke-occasionally",
    decorationStyle: "bright-colors",
    cleaningTasks: "clean-individual-stuff",
    bathroom: "absolutely",
    petPeeves: "Unsolicited advice",
    timeSpentInApartment: "never-in-apartment",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/05-megan.jpg'
  },
  {
    name: 'Gypsy Rose Blanchard',
    //age: 32,
    temperature_pref: "75-80",
    pets: "has-pets-open",
    sleepWakeHours: "morning-person",
    parties: "once-a-month",
    cleanlinessLevel: "fairly-clean-occasionally-messy",
    moveInDate: "immediately",
    relationshipStatus: "okay-with-partner",
    sharingItems: "prefer-ask",
    livingStyle: "just-live-together",
    drinkingHabits: "drink-no",
    smoking: "no-smoke",
    decorationStyle: "neutral-colors",
    cleaningTasks: "clean-individual-stuff",
    bathroom: "preferable",
    petPeeves: "Not having freedom to do what I want",
    timeSpentInApartment: "weekends-out",
    politicalStatus: "left",
    preferredAgeRange: null,
    profilePic: '/images/08-gypsy.jpg'
  }, 
];

const seedSurvey = () => Survey.bulkCreate(surveydata);

module.exports = seedSurvey;
